rvanbekkum/vsc-xliff-sync

CHANGELOG.md
README.md
package.json
src/features/trans-check.ts

You can now configure which technical validation rules should be run by command `XLIFF: Check for Need Work Translations`.
This can be done by the new setting `xliffSync.needWorkTranslationRules` which takes an array with rule IDs that should apply.
For now the allowed values are:
```json
"xliffSync.needWorkTranslationRules": [
"OptionMemberCount",
"OptionLeadingSpaces",
"Placeholders",
"SourceEqualsTarget"
]
```
This pull request introduces a new `SourceEqualsTarget`, which checks that the source and target are the same for files where source and target language are the same (e.g., when both are set to "en-US" for an .xlf file).
This closes #18.

New feature: Configurable rules + Rule SourceEqualsTarget

---

package.json
src/features/tools/files-helper.ts
src/features/tools/index.ts
src/features/tools/workspace-helper.ts
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts
src/features/trans-check.ts
src/features/trans-import.ts
src/features/trans-sync.ts

This pull request introduces support for multi-root workspaces.
You can have settings per workspace folder, each with their _own_ base XLIFF file.
The commands "XLIFF: Synchronize Translation Units", "XLIFF: Check for Missing Translations" and "XLIFF: Check for Need Work Translations" will run for each project folder in the workspace, but if a file from a specific project is opened, then the commands will run for the specific project folder only.
The command "XLIFF: Synchronize to Single File" will run for either the open file, or will prompt the user to select a workspace folder first. If there is only a single workspace folder, then it will not ask the user to select one.

Support for multi-root workspaces

---

CHANGELOG.md
README.md
package.json

Change the default for the `xliffSync.baseFile` setting to `g.xlf`.
Updates to the CHANGELOG and README accordingly.
Please see issue #34.

Default value for basefile setting to .g.xlf

---

package-lock.json
package.json
src/features/tools/files-helper.ts
src/features/trans-check.ts

* Only apply decorations in XLIFF files (not in every editor)
* Reload settings (i.e., `"xliffSync.decoration"`, `"xliffSync.decorationEnabled"`, `"xliffSync.decorationTargetTextOnly"`, `"xliffSync.missingTranslation"`) when switching active editor
* Add new setting `"xliffSync.decorationTargetTextOnly"` to have decorations only be applied to the target node's text, if enabled.
* Change highlight-update interval from 1 to 500 (ms)
Closes #39

Decoration Optimizations

---

CHANGELOG.md
README.md
package.json
src/features/tools/xlf-translator.ts

This PR adds the following new options:
* `xliffSync.detectSourceTextChanges` - Specifies whether changes in the source text of a trans-unit should be detected. If a change is detected, the target state is changed to needs-adaptation and a note is added to indicate the translation should be reviewed.
* `xliffSync.ignoreLineEndingTypeChanges` - Specifies whether changes in line ending type (CRLF vs. LF) should not be considered as changes to the source text of a trans-unit.
Updated README and CHANGELOG accordingly.
Resolves issue #41.

DetectSourceTextChanges and IgnoreLineEndingTypeChanges Options

---

CHANGELOG.md
README.md
package.json
src/extension.ts
src/features/snippets.ts
src/features/tools/xlf-translator.ts

* New setting `xliffSync.parseFromDeveloperNoteOverwrite` which when enabled will overwrite existing translations with the translations parsed from the Developer Note.
* New setting `xliffSync.copyFromSourceOverwrite` which when enabled will overwrite existing translations with the source text.
* The "Parse from Developer Note" feature will now also update translations if `xliffSync.missingTranslation` is configured to something other than the default value (which is missing translation = no translation).
* XLIFF Sync snippets for the "Parse from Developer Note" feature.
* You can configure for which programming languages the snippets should be available with setting `xliffSync.enableSnippetsForLanguages`. Currently only the "AL Language" is supported with snippets: …

Parse from Developer Note Enhancements

---

CHANGELOG.md
README.md
package.json
src/features/tools/files-helper.ts
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts
src/features/tools/xlf/xlf-translationState.ts
src/features/trans-check.ts

This PR makes various changes to better support XLIFF 2.0 files. Most notably, the states that are added to the nodes are now following the [XLIFF 2.0 specification](http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html).
Please see the updated CHANGELOG for more information.
Resolves #50.

Improved XLIFF 2.0 Support

---

package.json
src/features/tools/xlf/xlf-document.ts

Adds a setting `xliffSync.addNeedsWorkTranslationNote` that can be used to change whether an "XLIFF Sync" note should be added to trans-units that are being marked as needs-work by the extension (which are added to explain what was detected).

New setting to specify whether a needs-work translation note should be added

---

package.json
src/features/tools/files-helper.ts
src/features/trans-check.ts
src/features/trans-sync.ts

Adds a setting `xliffSync.openExternallyAfterEvent` that can be used to specify whether translation files should be opened automatically with the default XLIFF editor after an event takes place. By default, files will not be opened externally automatically.
You can set files to be opened externally automatically after:
* Checking translations
* Detecting problems
* Synchronizing translation files

New setting to automatically open files externally after certain events occur

---

CHANGELOG.md
package.json
src/features/tools/xlf/xlf-document.ts
src/features/trans-sync.ts

New setting `xliffSync.matchingOriginalOnly` that can be used to specify whether to sync. only to files where the `original` attribute of the `file`-node of an XLIFF file matches that of the base file (**Default**: `true`).

New setting xliffSync.matchingOriginalOnly

---

CHANGELOG.md
README.md
package.json
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts

New setting `xliffSync.clearTranslationAfterSourceTextChange` that can be used to specify whether the translation for trans-units should be cleared during syncing if a change in the source text is detected (instead of marking it as needs-work) (**Default**: `false`).

New setting xliffSync.clearTranslationAfterSourceTextChange

---

CHANGELOG.md
src/features/tools/xlf/xlf-document.ts

Do not add state attribute to (new) target nodes for XLIFF 2.0 files.
Issue #57.

Do not add state to target nodes for XLIFF 2.0

---

CHANGELOG.md
README.md
package.json
src/features/tools/files-helper.ts
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts
src/features/trans-check.ts
src/features/trans-import.ts
src/features/trans-sync.ts

* Activate extension when any of the extension's commands are invoked.
* New setting `xliffSync.matchingOriginalOnly` that can be used to specify whether to sync. only to files where the `original` attribute of the `file`-node of an XLIFF file matches that of the base file (**Default**: `true`). (GitHub issue [#51](https://github.com/rvanbekkum/vsc-xliff-sync/issues/51) + (GitHub issue [#66](https://github.com/rvanbekkum/vsc-xliff-sync/issues/66)))
* New setting `xliffSync.clearTranslationAfterSourceTextChange` that can be used to specify whether the translation for trans-units should be cleared during syncing if a change in the source text is detected (instead of marking it as needs-work) (**Default**: `false`). (GitHub issue [#64](https://github.com/rvanbekkum/vsc-xliff-sync/issues/64)) …

Release 0.7.0

---

CHANGELOG.md
README.md
package.json
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts

Optimized syncing through a preprocessing step that builds up unit maps. The existing implementation approaches O(n^2) while this optimization implemented brings it down to O(n) (with n being the number of translation units). This optimization was already applied earlier in the PowerShell version (see [ps-xliff-sync](https://github.com/rvanbekkum/ps-xliff-sync)). The new setting `xliffSync.unitMaps` can be used to change whether and to which extent these maps should be used (**Default**: `"All"`).

Handling Large Files

---

CHANGELOG.md
README.md
package.json
src/features/tools/xlf/xlf-document.ts

New setting `xliffSync.preserveTargetChildNodes` that can be used to specify whether child nodes specific to the translation target file should be preserved while syncing. Currently this setting will preserve `alt-trans` nodes and custom nodes for XLIFF 1.2 files. (**Default**: `false`) (GitHub issue [#60](https://github.com/rvanbekkum/vsc-xliff-sync/issues/60))

Preserve Target Child Nodes

---

CHANGELOG.md
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts
src/features/tools/xml-builder.ts
src/features/trans-check.ts
src/features/trans-import.ts

Properly handle units with child nodes (e.g., placeholder tags like `<x/>`) in the target node. The extension used to only expect strings as child node for `target` nodes.
Resolves #67.

Support translations with child-nodes

---

CHANGELOG.md
README.md
package.json
src/features/tools/files-helper.ts
src/features/trans-sync.ts

* New settings `xliffSync.equivalentLanguages` and `xliffSync.equivalentLanguagesEnabled` that can be used to specify equivalent languages. You can specify pairs of master language and slave language-pattern (RegEx) in the `xliffSync.equivalentLanguages` setting to have the extension copy to contents of the master language's translation file to the translation files of its slave languages. This way you only need to enter the translations for the master language, so that after you sync. again the slave languages will get the same translations, and you don't need to go through all languages files that would get the same translations. For example, _often_ `nl-NL` and `nl-BE` would simply get the same translations, so this way you could specify that `nl-BE` should take over all the …

New feature: Define equivalent languages

---

src/features/tools/xlf/xlf-document.ts

Fix for issue #81, introduced in the latest release.

Fix for new units getting state "translated" with empty content

---

src/features/trans-sync.ts

Use workspaceFolder value for `xliffSync.equivalentLanguages` setting.
Addresses problem reported in issue #87.

Patch equivalentLanguages (use workspaceFolder)

---

CHANGELOG.md
package-lock.json
package.json
src/features/trans-check.ts
src/features/trans-import.ts
src/features/trans-sync.ts

* Fixed "Open Externally" no longer working after Visual Studio Code update 1.57.0. This may be a work-around that will be reverted later on. (GitHub issue [#89](https://github.com/rvanbekkum/vsc-xliff-sync/issues/89))
* Patch "equivalent languages" feature not allowing to override default value but instead merging the setting values (this was not intended). (GitHub issue [#87](https://github.com/rvanbekkum/vsc-xliff-sync/issues/87))
Updated CHANGELOG accordingly.

Release 1.2.0

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/features/tools/files-helper.ts
src/features/tools/workspace-helper.ts
src/features/tools/xlf-translator.ts
src/features/tools/xlf/xlf-document.ts
src/features/trans-check.ts
src/features/trans-import.ts
src/features/trans-sync.ts
tsconfig.json

* New setting `xliffSync.parseFromDeveloperNoteTrimCharacters` that can be used to specify the characters to trim from the translations parsed from the developer notes. (GitHub issue [#100](https://github.com/rvanbekkum/vsc-xliff-sync/issues/100))
* Included `needs-l10n` to be considered as a needs-work state. (GitHub issue [#102](https://github.com/rvanbekkum/vsc-xliff-sync/issues/102))
Updated CHANGELOG accordingly.

Release 1.3.0

---

README.md
package.json
src/features/tools/xlf/xlf-document.ts
src/features/tools/xml-builder.ts

add a new setting called `useSelfClosingTags` which allow to define how empty tag must be write while generating new XLIFF synchronized files.
its default value is `true` meaning empty tag will use self closing format (`<note/>`) - as it was the case prior this change.
when set to `false`, empty tag will be write using opening and closing format (`<note></note>`).
as an example, AL Compiler is using the opening and closing format instead the self-closing one.
using this extension current version with AL project is then generating excessive git diff for small changes since all empty tags are updated to the self-closing format.
references :
- https://github.com/oozcitak/xmlbuilder-js/issues/65
- https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string
Closes #97

feat: add ability to define empty tag format
